# Generated by Django 5.0.2 on 2025-06-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='event',
            name='duration_hours',
            field=models.FloatField(blank=True, help_text='Длительность мероприятия в часах', null=True),
        ),
    ]
