# Generated by Django 4.2 on 2025-06-25 16:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_rename_volunteer_to_scanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
            ],
            options={
                'verbose_name': 'Тим лидер',
                'verbose_name_plural': 'Тим лидеры',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='scanner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
