# Generated by Django 4.2 on 2025-06-27 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='leader',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='volunteers_required',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='late_minutes',
        ),
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.CharField(default='DEFAULT000', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Астана', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='max_scanners',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scanner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_hours',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TeamLeaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
